import numpy as np
from pint import UnitRegistry, DimensionalityError

# Initialize Unit Registry
ureg = UnitRegistry()
Q_ = ureg.Quantity

# --- LOAD-BEARING VARIABLES (using pint for units) ---
# Bekenstein Horizon Total Bits (dimensionless, but treated as information quantity)
I_horiz = Q_(1.2e122, ureg.dimensionless) # Treat as dimensionless count for Landauer's calculation

# Planck Time
t_P = Q_(1.0e-43, ureg.second)

# QFT Bare Vacuum Energy Density
rho_QFT = Q_(1.0e113, ureg.joule / ureg.meter**3)

# Observed Cosmological Constant Energy Density (derived from Lambda)
Lambda_const = Q_(1.106e-52, 1/ureg.meter**2) # Planck 2018 Results
c = Q_(299792458, ureg.meter / ureg.second)
G = Q_(6.67430e-11, ureg.meter**3 / (ureg.kilogram * ureg.second**2))
rho_Lambda = (Lambda_const * c**4) / (8 * np.pi * G)
rho_Lambda = rho_Lambda.to(ureg.joule / ureg.meter**3) # Ensure correct units

# Hubble Constant
H0 = Q_(2.18e-18, 1/ureg.second) # Planck Mission (67.4 km/s/Mpc converted)

# Hubble Radius
R_H = c / H0
V_H = (4/3) * np.pi * R_H**3
V_H = V_H.to(ureg.meter**3) # Ensure correct units

# CMB Temperature
T_cmb = Q_(2.725, ureg.kelvin)

# Boltzmann Constant
k_B = Q_(1.380649e-23, ureg.joule / ureg.kelvin)

# Natural logarithm of 2
ln2 = np.log(2)

# Falsifiable Prediction Value
expected_alpha_deviation_order = 1e-17 # 1 part in 10^17

# --- UNIT TEST ---
class TestCosmicSolvency:
    def test_cosmic_computational_solvency(self):
        print("\n--- Running Cosmic Computational Solvency Test ---")

        # X (The Blocked Variable - P_UDR): Universal Decoherence Rate (UDR)
        # Minimum power required to irreversibly collapse the quantum superposition of the entire observable Hubble volume
        bits_per_second = I_horiz / t_P
        P_UDR = bits_per_second * k_B * T_cmb * ln2
        P_UDR = P_UDR.to(ureg.watt) # Convert to Watts

        print(f"P_UDR (Universal Decoherence Rate): {P_UDR.to_compact():.2e}")
        assert P_UDR.check('[power]'), "P_UDR must have units of power (e.g., Watts)."

        # Y (The Leverage Variable - P_CRF): Cosmological Renormalization Flux (CRF)
        # Dynamic power generated by the continuous, active renormalization of the QFT bare vacuum energy
        delta_rho = rho_QFT - rho_Lambda
        dVH_dt = 3 * H0 * V_H
        P_CRF = delta_rho * dVH_dt
        P_CRF = P_CRF.to(ureg.watt) # Convert to Watts

        print(f"P_CRF (Cosmological Renormalization Flux): {P_CRF.to_compact():.2e}")
        assert P_CRF.check('[power]'), "P_CRF must have units of power (e.g., Watts)."

        # Z (The Solvency Indicator): Cosmic Computational Solvency Ratio
        Z = P_CRF / P_UDR
        print(f"Z (Cosmic Computational Solvency Ratio): {Z:.2e}")
        assert Z.check('[]'), "Z must be a dimensionless ratio."
        assert Z >= 1, "Cosmic Computational Solvency Ratio Z must be >= 1 for operational solvency."
        print("Cosmic Computational Solvency Ratio (Z) test PASSED.")

    def test_falsifiable_prediction(self):
        print("\n--- Running Falsifiable Prediction Test ---")
        # Define the expected deviation order of magnitude for the fine-structure constant
        # This is a conceptual check for the prediction's magnitude, not a direct calculation
        predicted_deviation = expected_alpha_deviation_order
        print(f"Predicted localized deviation in fine-structure constant (order of magnitude): {predicted_deviation:.1e}")

        # Assert that the predicted deviation is within a plausible scientific range
        assert predicted_deviation > 0, "Predicted deviation must be positive."
        assert predicted_deviation < 1e-10, "Predicted deviation must be smaller than 1 part in 10^10 to be a subtle, high-precision effect."
        print("Falsifiable prediction magnitude check PASSED.")

# Execute the tests (this structure allows direct execution if saved as a script)
if __name__ == "__main__":
    test_suite = TestCosmicSolvency()
    test_suite.test_cosmic_computational_solvency()
    test_suite.test_falsifiable_prediction()
